POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "name":"ritik",
    "email":"cs.ritik@gmail.com",
    "password":"Ritik"
}

#####

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"cs.ritik@gmail.com",
    "password":"Ritik"
}